db_path: "data/gas_monitoring.db"
numerical_features:
  - Temperature_x_Humidity
  - CO2_sum
  - MetalOxideSensor_sum
nominal_features:
  - HVAC Operation Mode
ordinal_features:
  - Time of Day
  - Session_ID_Bands
  - CO_GasSensor
param_grids:
  DecisionTree:
    classifier__max_depth:
      - 3
      - 5
      - 7
      - 10
      - null
    classifier__min_samples_split:
      - 2
      - 5
      - 10
    classifier__min_samples_leaf:
      - 1
      - 2
      - 4
  RandomForest:
    classifier__n_estimators:
      - 50
      - 100
      - 200
    classifier__max_depth:
      - 3
      - 5
      - 10
      - null
    classifier__min_samples_split:
      - 2
      - 5
      - 10
    classifier__min_samples_leaf:
      - 1
      - 2
      - 4
  LogisticRegression:
    classifier__C:
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
    classifier__solver:
      - lbfgs
      - saga
  XGBoost:
    classifier__n_estimators:
      - 50
      - 100
      - 200
    classifier__max_depth:
      - 3
      - 5
      - 7
    classifier__learning_rate:
      - 0.01
      - 0.1
      - 0.3
    classifier__subsample:
      - 0.6
      - 0.8
      - 1.0
